/*
 * stm32f407xx.h
 *
 *  Created on: 7 Ağu 2023
 *      Author: ASUS
 */
#include <stdint.h>
#ifndef STM32F407XX_H_
#define STM32F407XX_H_

#define PUBLIC
#define PRIVATE 	static

#define PERIPHERAL_BASE_ADDR        0x40000000U//u unsigned anlamında
#define APB1_PERIPHERAL_BASE_ADDR   PERIPHERAL_BASE_ADDR//aynı adres
#define APB2_PERIPHERAL_BASE_ADDR   0x40010000U
#define AHB1_PERIPHERAL_BASE_ADDR   0x40020000U
#define AHB2_PERIPHERAL_BASE_ADDR   0x50050000U
#define AHB3_PERIPHERAL_BASE_ADDR   0x60000000U
//busların adreslerini yazdık 0x60000000U
//busların adreslerini yazdık

#define TIM2_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x00)
#define TIM3_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x0400)
#define TIM4_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x0800)
#define TIM5_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x0C00)
#define TIM6_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x1000)
#define TIM7_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x1400)
#define TIM12_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x1800)
#define TIM13_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x1C00)
#define TIM14_BASEADDR 			    (APB1_PERIPHERAL_BASE_ADDR+0x2000)
//Timerlerin aadresleri

#define RTC_BKP_BASEADDR            (APB1_PERIPHERAL_BASE_ADDR+0x2800)
#define WWDG_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x2C00)
#define IWDG_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x3000)
#define I2S2ext_BASEADDR            (APB1_PERIPHERAL_BASE_ADDR+0x3400)


#define SPI2_I2S2_BASEADDR          (APB1_PERIPHERAL_BASE_ADDR+0x3800)
#define SPI3_I2S3_BASEADDR          (APB1_PERIPHERAL_BASE_ADDR+0x3C00)
#define I2S3ext_BASEADDR            (APB1_PERIPHERAL_BASE_ADDR+0x4000)
#define USART2_BASEADDR             (APB1_PERIPHERAL_BASE_ADDR+0x4400)
#define USART3_BASEADDR             (APB1_PERIPHERAL_BASE_ADDR+0x4800)
#define USART4_BASEADDR             (APB1_PERIPHERAL_BASE_ADDR+0x4C00)
#define USART5_BASEADDR             (APB1_PERIPHERAL_BASE_ADDR+0x5000)
#define I2C1_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x5400)
#define I2C2_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x5800)
#define I2C3_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x5C00)
#define CAN1_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x6400)
#define CAN2_BASEADDR               (APB1_PERIPHERAL_BASE_ADDR+0x6800)
#define PWR_BASEADDR                (APB1_PERIPHERAL_BASE_ADDR+0x7000)
#define DAC_BASEADDR                (APB1_PERIPHERAL_BASE_ADDR+0x7400)

//APB2 bus base addresleri

#define TIM1_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x00)
#define TIM8_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x0400)
#define USART1_BASEADDR             (APB2_PERIPHERAL_BASE_ADDR+0x1000)
#define USART6_BASEADDR             (APB2_PERIPHERAL_BASE_ADDR+0x1400)
#define ADC1_2_3_BASEADDR           (APB2_PERIPHERAL_BASE_ADDR+0x2000)
#define SDIO_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x2C00)
#define SPI1_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x3000)
#define SYSCFG_BASEADDR             (APB2_PERIPHERAL_BASE_ADDR+0x3800)
#define EXTI_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x3C00)
#define TIM9_BASEADDR               (APB2_PERIPHERAL_BASE_ADDR+0x4000)
#define TIM10_BASEADDR              (APB2_PERIPHERAL_BASE_ADDR+0x4400)
#define TIM11_BASEADDR              (APB2_PERIPHERAL_BASE_ADDR+0x4800)

//AHB1 bus base addresses

#define GPIOA_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x00)
#define GPIOB_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x0400)
#define GPIOC_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x0800)
#define GPIOD_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x0C00)
#define GPIOE_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x1000)
#define GPIOF_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x1400)
#define GPIOG_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x1800)
#define GPIOH_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x1C00)
#define GPIOI_BASEADDR              (AHB1_PERIPHERAL_BASE_ADDR+0x2000)
#define CRC_BASEADDR                (AHB1_PERIPHERAL_BASE_ADDR+0x3000)
#define RCC_BASEADDR                (AHB1_PERIPHERAL_BASE_ADDR+0x3800)
#define FLASH_INTERFACE_BASEADDR    (AHB1_PERIPHERAL_BASE_ADDR+0x3C00)
#define BKPSRAM_BASEADDR            (AHB1_PERIPHERAL_BASE_ADDR+0x4000)
#define DMA1_BASEADDR               (AHB1_PERIPHERAL_BASE_ADDR+0x6000)
#define DMA2_BASEADDR               (AHB1_PERIPHERAL_BASE_ADDR+0x6400)
#define ETHERNET_MAC_BASEADDR       (AHB1_PERIPHERAL_BASE_ADDR+0x8000)
#define USB_OTG_HS_BASEADDR         (0x40040000U)
#define USB_OTG_FS_BASEADDR         (0x50000000U)

//AHB2 base addresses
#define DCMI_BASEADDR               (AHB2_PERIPHERAL_BASE_ADDR+0x00)
#define RNG_BASEADDR                (AHB2_PERIPHERAL_BASE_ADDR+0x10800)

//AHB3 base addresses
#define FSMC_BANK1_BASEADDR               (AHB3_PERIPHERAL_BASE_ADDR+0x6000)
#define FSMC_BANK2_BASEADDR               (AHB3_PERIPHERAL_BASE_ADDR+0x6000)
#define FSMC_BANK3_BASEADDR               (AHB3_PERIPHERAL_BASE_ADDR+0x6000)
#define FSMC_CONTROL_REGISTER_BASEADDR    (AHB3_PERIPHERAL_BASE_ADDR+0x6000)


typedef volatile uint32_t IO_;
typedef struct{
	IO_ CR;
	IO_ PLLCFGR;
	IO_ CFGR;
	IO_ CIR;
	IO_ AHB1RSTR;
	IO_ AHB2RSTR;
	IO_ AHB3RSTR;
	uint32_t RESERVED0;
	IO_ APB1RSTR;
	IO_ APB2RSTR;
	uint32_t RESERVED1_2[2];
	IO_ AHB1ENR;
	IO_ AHB2ENR;
	IO_ AHB3ENR;
	uint32_t RESERVED3;
	IO_ APB1ENR;
	IO_ APB2ENR;
	uint32_t RESERVED4_5[2];
	IO_ AHB1LPENR;
	IO_ AHB2LPENR;
	IO_ AHB3LPENR;
	uint32_t RESERVED6;
	IO_ APB1LPENR;
	IO_ APB2LPENR;
	uint32_t RESERVED7_8[2];
	IO_ BDCR;
	IO_ CSR;
	uint32_t RESERVED9_10[2];
	IO_ SSCGR;
	IO_ PLLI2SCFGR;
	IO_ PLLSAICFGR;
	IO_ DCKCFGR;
}RCC_RegDef_t;


typedef struct{
	IO_ MODER;
	IO_ OTYPER;
	IO_ OSPEEDR;
	IO_ PUPDR;
	IO_ IDR;
	IO_ ODR;
	IO_ LCKR;
	IO_ AFR[2];//AFR[0]--->LOW	AFR[1]--->HIGH
}GPIO_RegDef_t;

#define GPIOA		((GPIO_RegDef_t*)GPIOA_BASEADDR)
#define GPIOB		((GPIO_RegDef_t*)GPIOB_BASEADDR)
#define GPIOC		((GPIO_RegDef_t*)GPIOC_BASEADDR)
#define GPIOD		((GPIO_RegDef_t*)GPIOD_BASEADDR)
#define GPIOE		((GPIO_RegDef_t*)GPIOE_BASEADDR)
#define GPIOF		((GPIO_RegDef_t*)GPIOF_BASEADDR)
#define GPIOG		((GPIO_RegDef_t*)GPIOG_BASEADDR)
#define GPIOH		((GPIO_RegDef_t*)GPIOH_BASEADDR)
#define GPIOI		((GPIO_RegDef_t*)GPIOI_BASEADDR)


#define RCC			((RCC_RegDef_t*)RCC_BASEADDR)

#define GPIOA_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<0))
#define GPIOB_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<1))
#define GPIOC_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<2))
#define GPIOD_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<3))
#define GPIOE_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<4))
#define GPIOF_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<5))
#define GPIOG_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<6))
#define GPIOH_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<7))
#define GPIOI_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<8))

#define SYSCFGR_CLOCK_ENABLE()  (RCC->APB2ENR |= (1u<<14))

#define TIMER1_CLOCK_ENABLE()	(RCC->APB2ENR |= (1<<0))
#define TIMER2_CLOCK_ENABLE()	(RCC->APB1ENR |= (1<<0))
#define TIMER3_CLOCK_ENABLE()	(RCC->APB1ENR |= (1<<1))
#define TIMER4_CLOCK_ENABLE()	(RCC->APB1ENR |= (1<<2))
#define TIMER5_CLOCK_ENABLE()	(RCC->APB1ENR |= (1<<3))
#define TIMER6_CLOCK_ENABLE()	(RCC->APB1ENR |= (1<<4))
#define TIMER7_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1<<5))
#define TIMER8_CLOCK_ENABLE()	(RCC->APB2ENR |= (1<<1))
#define TIMER9_CLOCK_ENABLE()	(RCC->APB2ENR |= (1<<16))
#define TIMER10_CLOCK_ENABLE()	(RCC->APB2ENR |= (1<<17))
#define TIMER11_CLOCK_ENABLE()	(RCC->APB2ENR |= (1<<18))

typedef struct{
	IO_ CR;
	IO_ SR;
	IO_ DR;
}RNG_RegDef_t;

#define RNG 		            ((RNG_RegDef_t*)RNG_BASEADDR)

#define RNG_CLOCK_ENABLE() 		(RCC->AHB2ENR |= (1<<6))

typedef struct{
	IO_ IMR;
	IO_ EMR;
	IO_ RTSR;
	IO_ FTSR;
	IO_ SWIER;
	IO_ PR;
}EXTI_RegDef_t;


#define EXTI					((EXTI_RegDef_t*)EXTI_BASEADDR)
//syscfg register

typedef struct{
	IO_ MEMRMP;
	IO_ PMC;
	IO_ EXTICR1;
	IO_ EXTICR2;
	IO_ EXTICR4;
	IO_ CMPCR;
}SYSCFG_RegDef;

#define SYSCFG					((SYSCFG_RegDef*)SYSCFG_BASEADDR)
//timer register
typedef struct{
	IO_ CR1;
	IO_ CR2;
	IO_ SMCR;
	IO_ DIER;
	IO_ SR;
	IO_ EGR;
	IO_ CCMR1;
	IO_ CCMR2;
	IO_ CCER;
	IO_ CNT;
	IO_ PSC;
	IO_ ARR;
	IO_ RCR;
	IO_ CCR1;
	IO_ CCR2;
	IO_ CCR3;
	IO_ CCR4;
	IO_ BDTR;
	IO_ DCR;
	IO_ DMAR;
	IO_ OR;
} TIM_RegDef_t;

typedef struct{
	IO_ SR;
	IO_ DR;
	IO_ BRR;
	IO_ CR1;
	IO_ CR2;
	IO_ CR3;
	IO_ GTPR;
}UART_RegDef_t;

#define  TIMER1					((TIM_RegDef_t*)TIM1_BASEADDR)
#define  TIMER2					((TIM_RegDef_t*)TIM2_BASEADDR)
#define  TIMER3					((TIM_RegDef_t*)TIM3_BASEADDR)
#define  TIMER4					((TIM_RegDef_t*)TIM4_BASEADDR)
#define  TIMER5					((TIM_RegDef_t*)TIM5_BASEADDR)
#define  TIMER6					((TIM_RegDef_t*)TIM6_BASEADDR)
#define  TIMER7					((TIM_RegDef_t*)TIM7_BASEADDR)
#define  TIMER8					((TIM_RegDef_t*)TIM8_BASEADDR)
#define  TIMER9					((TIM_RegDef_t*)TIM9_BASEADDR)
#define  TIMER10				((TIM_RegDef_t*)TIM10_BASEADDR)

#define USART1 ((UART_RegDef_t*)USART1_BASEADDR)
#define USART2 ((UART_RegDef_t*)USART2_BASEADDR)
#define USART3 ((UART_RegDef_t*)USART3_BASEADDR)
#define USART4 ((UART_RegDef_t*)USART4_BASEADDR)
#define USART5 ((UART_RegDef_t*)USART5_BASEADDR)
#define USART6 ((UART_RegDef_t*)USART6_BASEADDR)

#define USART1_CLOCK_ENABLE() (RCC->APB2ENR |= (1<<4))
#define USART2_CLOCK_ENABLE() (RCC->APB1ENR |= (1<<17))
#define USART3_CLOCK_ENABLE() (RCC->APB1ENR |= (1<<18))
#define USART4_CLOCK_ENABLE() (RCC->APB1ENR |= (1<<19))
#define USART5_CLOCK_ENABLE() (RCC->APB1ENR |= (1<<20))
#define USART6_CLOCK_ENABLE() (RCC->APB2ENR |= (1<<5))



#endif /* STM32F407XX_H_ */
