/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"
#include "stm32f407xx.h"
#include <TIM.h>
#include <Arm_Cortex_M4.h>
#include <RNG.h>
#include "LCD.h"
#include "usart.h"

void delay()
{
    for(int i=0;i<1000000000;++i);
}

void Task_Led(){


	static enum{
		S_LED_OFF,
		S_LED_ON,
	}state  = S_LED_OFF;

	static clock_t t0;//duruma ilk giriş saati
	static clock_t t1;//güncel giriş saati
	t1 = clock();

	switch(state){
	case S_LED_OFF:
		if (t1>=t0+800){
			Gpio_Write_Output_Pin(GPIOD, GPIO_PIN_NO_15, GPIO_PIN_SET);
			t0=t1;
			state = S_LED_ON;
			}
		break;
	case S_LED_ON:
		if (t1>=t0+200){
			Gpio_Write_Output_Pin(GPIOD, GPIO_PIN_NO_15, GPIO_PIN_RESET);
			t0=t1;
			state = S_LED_OFF;
			}
		break;
	}
}

int main(void)
{
	/*
	Gpio_Handle_t Gpio_Pd;

	Gpio_Pd.pGpioX = GPIOD;//register address GPIO_RegDef_t türünden
	Gpio_Pd.Gpio_PinConfig.PinMode = GPIO_MODE_OUT;
	Gpio_Pd.Gpio_PinConfig.PinNumber =GPIO_PIN_NO_14;
	Gpio_Pd.Gpio_PinConfig.PinOtype = GPIO_OTYPE_PP;
	Gpio_Pd.Gpio_PinConfig.PinPuPd = GPIO_PIN_PUPD_NO;
	Gpio_Pd.Gpio_PinConfig.PinSpeed = GPIO_SPEED_MEDIUM;
	*/

	//Gpio_Handle_t Gpio_pd_blue = {GPIOD,{GPIO_PIN_NO_15,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO}};//tek satırda initialize ettik
	Gpio_Handle_t Gpio_pd_green = {GPIOD,{GPIO_PIN_NO_12,GPIO_MODE_ALTERNATE,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO,GPIO_AF2}};//tek satırda initialize ettik
	//Gpio_Handle_t Gpio_pd_red = {GPIOD,{GPIO_PIN_NO_14,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO}};//tek satırda initialize ettik
	//Gpio_Handle_t Gpio_pd_orange = {GPIOD,{GPIO_PIN_NO_13,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO}};//tek satırda initialize ettik

	//pio_Handle_t Gpio_pd_blue_ = {GPIOD,{GPIO_PIN_NO_15,GPIO_MODE_ALTERNATE,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO,GPIO_AF15}};//tek satırda reinitialize ettik
	//Gpio_Init(&Gpio_pd_blue);//15 numaralı pini initialize ettik
	Gpio_Init(&Gpio_pd_green);//12 numaralı pini initialize ettik
	//Gpio_Init(&Gpio_pd_red);//14 numaralı pini initialize ettik
	//Gpio_Init(&Gpio_pd_orange);//13 numaralı pini initialize ettik
	//Gpio_Init(&Gpio_pd_blue_);//15 numaralı pini reinitialize ettik
	/*
	Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_GREEN,GPIO_PIN_SET);
	Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_BLUE,GPIO_PIN_SET);
	Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_RED,GPIO_PIN_SET);
	Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_ORANGE,GPIO_PIN_SET);

	Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_BLUE,GPIO_PIN_RESET);
	*/
	//reseti kontrol ettik


	//user button interrupt

	/*
	Gpio_Handle_t user_button;
	user_button.pGpioX = GPIOA;
	user_button.Gpio_PinConfig.PinNumber = GPIO_PIN_NO_0;
	user_button.Gpio_PinConfig.PinMode = GPIO_MODE_FE_IT;
	user_button.Gpio_PinConfig.PinPuPd = GPIO_PIN_PUPD_NO;
	Gpio_Init(&user_button);
	Gpio_Handle_t Gpio_pd_blue = {GPIOD,{GPIO_PIN_NO_15,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_PIN_PUPD_NO}};
	Gpio_Init(&Gpio_pd_blue);

	NVIC_Interrupt_Enable(IRQn_EXTI0);
	*/
	//Systick_Config(SYSTEM_FREQ/1000);//1ms de bir kesme
	//lcd_init();
	//lcd_print_char('b');
	//lcd_print_string("samet");
	//timer_init(TIMER_6, 16000000/2000, 1000, 0);
	//timer_interrupt_config(TIMER_6);
	//output_compare_init(TIMER_4, 1600, 1000, 1000);//TIMER4 CH1
	USART_Handle_t usart1_handle;
	usart1_handle.pUsartX = USART1;
	usart1_handle.usart_Config.mode= USART_MODE_BOTH_TXRX;
	usart1_handle.usart_Config.word_length = USART_WORDLEN_8BITS;
	usart1_handle.usart_Config.stop_bit = USART_STOPBITS_1;
	usart1_handle.usart_Config.parity_control=USART_PARITY_NO;
	usart1_handle.usart_Config.hwflowcontrol = USART_HW_FLOW_CONTROL_NO;

	while(1){

		//Gpio_Toggle_Output_Pin(GPIOD,GPIO_PIN_ORANGE);
		/*
		Gpio_Write_Output_Port(GPIOD,GPIO_PORT_PIN_BLUE|GPIO_PORT_PIN_RED|GPIO_PORT_PIN_ORANGE|GPIO_PORT_PIN_GREEN);//output port fonksiyonunu kontrol ettik
		Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_GREEN,GPIO_PIN_RESET);//yeşili söndürdüm
		Gpio_Write_Output_Port(GPIOD,GPIO_PORT_RAINBOW);//tüm ledleri yakan makroyu kullandık
		Gpio_Write_Output_Pin(GPIOD,GPIO_PIN_ORANGE,GPIO_PIN_RESET);//turuncuyu söndürdüm
		Gpio_Write_Output_Port(GPIOD,GPIO_PORT_ALL_LEDS);//tüm ledleri yakan makroyu kullandık
		*/
		//Task_Led();




}
}


